name: Sync Conda Environment

on:
  push:

jobs:
  update-requirements:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Convert requirements.txt to environment.yml
        run: |
          python - <<EOF
          requirements_file = "requirements.txt"
          output_file = "environment.yml"
          python_version= "3.10"

          with open(requirements_file, "r") as f:
              pip_packages = [
                  line.strip()
                  for line in f
                  if line.strip() and not line.strip().startswith("#")
              ]

          with open(output_file, "w") as f:
              f.write("name: streamlit-template\n")
              f.write("dependencies:\n")
              f.write(f"  - python={python_version}\n")  # Adjust Python version if needed
              f.write("  - pip\n")
              f.write("  - pip:\n")
              for package in pip_packages:
                  f.write(f"      - {package}\n")

          print(f"Converted {requirements_file} to {output_file}")
          EOF

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update environment.yml from requirements.txt"
          file_pattern: "environment.yml"

